### ISSUE TITLE
Upgrade request for latte-integrale to version 1.7.6

### ISSUE THREAD

**Issue by xuluze** [conda-forge/latte-integrale-feedstock#3]
### Comment:

Hello,

I am wondering if it is possible to upgrade latte-integrale to version 1.7.6 on conda-forge.
I am trying to use the "count" function via multivariate_generating_function. The code works in version 1.7.6, but report the following bug in version 1.7.5:

```
File ~/sage/src/sage/interfaces/latte.py:195, in count(arg, ehrhart_polynomial, multivariate_generating_function, raw_output, verbose, **kwds)
    193         return R(ans)
    194 elif multivariate_generating_function:
--> 195     with open(filename + '.rat') as f:
    196         ans = f.read()
    197     if raw_output:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp16313yfc/tmp_pg_so41n.rat'
```

Thank you very much!

Best,
Luze

**Comment by saraedum** [comment]
@xuluze, yes absolutely. Could you try to create a Pull Request that updates the `meta.yaml` file here?

**Comment by saraedum** [comment]
@xuluze we are now just pushing this through even though tests are failing. Unfortunately, upstream does not respond to requests for help. Neither here, nor in the latte-integrale repository. If you happen to have any connection to the authors, feel free to reach out to them.
